# Generated by Django 5.2.14 on 2026-05-15 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="名称")),
                ("url", models.URLField(max_length=512, verbose_name="Webhook URL")),
                (
                    "secret",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="签名密钥"
                    ),
                ),
                (
                    "events",
                    models.CharField(
                        blank=True,
                        default="info,success,warning,error",
                        help_text="逗号分隔的通知类型，空=全部",
                        max_length=256,
                        verbose_name="触发事件",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Webhook 配置",
                "verbose_name_plural": "Webhook 配置",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "response_status",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="HTTP 状态码"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, default="", verbose_name="响应内容"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notification.notification",
                        verbose_name="关联通知",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notification.webhookconfig",
                        verbose_name="Webhook 配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook 发送日志",
                "verbose_name_plural": "Webhook 发送日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
