# Generated by Django 5.2.14 on 2026-05-11 09:28

import djangoadminx.config_center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, default='', verbose_name='配置值')),
                ('value_type', models.CharField(choices=[('string', '字符串'), ('int', '整数'), ('bool', '布尔'), ('json', 'JSON'), ('encrypted', '加密')], default='string', max_length=20, verbose_name='值类型')),
                ('encrypted_value', djangoadminx.config_center.models.EncryptedConfigField(blank=True, default='', max_length=1024, verbose_name='加密值')),
                ('desc', models.CharField(blank=True, default='', max_length=500, verbose_name='描述')),
                ('group', models.CharField(blank=True, default='default', max_length=128, verbose_name='分组')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
                'ordering': ['group', 'key'],
            },
        ),
    ]
