# Generated by Django 5.2.14 on 2026-05-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_center", "0004_migrate_encrypted_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("string", "字符串"),
                    ("int", "整数"),
                    ("bool", "布尔"),
                    ("json", "JSON"),
                    ("options", "选项列表"),
                ],
                default="string",
                max_length=20,
                verbose_name="值类型",
            ),
        ),
    ]
