# Generated by Django 5.2.14 on 2026-05-11 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_length', models.IntegerField(default=8, verbose_name='最小长度')),
                ('require_upper', models.BooleanField(default=True, verbose_name='需要大写字母')),
                ('require_lower', models.BooleanField(default=True, verbose_name='需要小写字母')),
                ('require_digit', models.BooleanField(default=True, verbose_name='需要数字')),
                ('require_special', models.BooleanField(default=True, verbose_name='需要特殊字符')),
                ('expire_days', models.IntegerField(default=90, help_text='0=不过期', verbose_name='密码过期天数')),
                ('history_count', models.IntegerField(default=5, help_text='禁止复用最近N次', verbose_name='历史密码保留数')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '密码策略',
                'verbose_name_plural': '密码策略',
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=256, verbose_name='密码哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '密码历史',
                'verbose_name_plural': '密码历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
