# Generated by Django 5.2.14 on 2026-05-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="allowed_paths",
            field=models.TextField(
                blank=True,
                default="[]",
                help_text='JSON 数组，格式同 BusinessCommand，如 ["GET:/api/v1/menu/*"]',
                verbose_name="接口路径白名单",
            ),
        ),
    ]
