# Generated by Django 5.2.14 on 2026-05-11 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('handler', models.CharField(help_text='如 djangoadminx.webservice.tasks.sync_data', max_length=255, verbose_name='处理函数')),
                ('trigger_type', models.CharField(choices=[('cron', 'Cron'), ('interval', '间隔'), ('date', '指定时间')], default='interval', max_length=20, verbose_name='触发类型')),
                ('trigger_config', models.TextField(blank=True, default='', help_text='JSON 格式，如 {"minutes": 5}', verbose_name='触发配置')),
                ('args', models.TextField(blank=True, default='', help_text='JSON 数组', verbose_name='参数')),
                ('kwargs', models.TextField(blank=True, default='{}', help_text='JSON 对象', verbose_name='关键字参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='服务名称')),
                ('wsdl_url', models.URLField(blank=True, default='', verbose_name='WSDL 地址')),
                ('type', models.CharField(choices=[('publish', '发布'), ('consume', '调用')], default='consume', max_length=20, verbose_name='类型')),
                ('method', models.CharField(blank=True, default='', max_length=128, verbose_name='方法名')),
                ('request_template', models.TextField(blank=True, default='', help_text='JSON 模板，供前端填写参数', verbose_name='请求模板')),
                ('response_mapping', models.TextField(blank=True, default='', help_text='响应字段映射配置', verbose_name='响应映射')),
                ('auth_type', models.CharField(choices=[('none', '无'), ('basic', 'Basic'), ('token', 'Token')], default='none', max_length=20, verbose_name='认证类型')),
                ('auth_username', models.CharField(blank=True, default='', max_length=128, verbose_name='认证用户名')),
                ('auth_password', models.CharField(blank=True, default='', max_length=256, verbose_name='认证密码')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WebService 配置',
                'verbose_name_plural': 'WebService 配置',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('result', models.TextField(blank=True, default='', verbose_name='结果')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.schedulejob', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='schedulejob',
            name='webservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webservice.webservice', verbose_name='关联 WebService'),
        ),
        migrations.CreateModel(
            name='WebServiceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=128, verbose_name='方法')),
                ('request_body', models.TextField(blank=True, default='', verbose_name='请求')),
                ('response_body', models.TextField(blank=True, default='', verbose_name='响应')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='状态')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('cost_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.webservice', verbose_name='服务')),
            ],
            options={
                'verbose_name': 'WebService 日志',
                'verbose_name_plural': 'WebService 日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
