# Generated by Django 5.2.14 on 2026-05-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulejob',
            name='command',
            field=models.TextField(blank=True, default='', help_text='command_type=shell 时，要执行的命令或脚本', verbose_name='Shell 命令'),
        ),
        migrations.AddField(
            model_name='schedulejob',
            name='command_type',
            field=models.CharField(choices=[('python', 'Python 函数'), ('shell', 'Shell 命令')], default='python', max_length=20, verbose_name='命令类型'),
        ),
        migrations.AlterField(
            model_name='schedulejob',
            name='handler',
            field=models.CharField(blank=True, default='', help_text='如 djangoadminx.webservice.tasks.sync_data', max_length=255, verbose_name='处理函数'),
        ),
    ]
