# Generated by Django 5.2.14 on 2026-05-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='菜单编码')),
                ('name', models.CharField(max_length=128, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, default='', max_length=64, verbose_name='图标')),
                ('path', models.CharField(blank=True, default='', max_length=512, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, default='', max_length=512, verbose_name='组件路径')),
                ('permission_code', models.CharField(blank=True, default='', help_text='如 accounts:user:list，空表示不需要权限', max_length=256, verbose_name='权限编码')),
                ('menu_type', models.CharField(choices=[('menu', '菜单'), ('button', '按钮'), ('iframe', 'Iframe')], default='menu', max_length=20, verbose_name='菜单类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['sort_order'],
            },
        ),
    ]
