# Generated by Django 5.2.14 on 2026-05-11 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除')], max_length=20, verbose_name='操作类型')),
                ('model_name', models.CharField(db_index=True, max_length=128, verbose_name='模型名')),
                ('object_id', models.CharField(blank=True, default='', max_length=128, verbose_name='对象ID')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='对象描述')),
                ('operator', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='操作人')),
                ('operator_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('old_values', models.JSONField(blank=True, default=None, null=True, verbose_name='变更前')),
                ('new_values', models.JSONField(blank=True, default=None, null=True, verbose_name='变更后')),
                ('diff_summary', models.CharField(blank=True, default='', max_length=500, verbose_name='变更摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx')],
            },
        ),
    ]
