# Generated by Django 5.2.14 on 2026-05-11 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='节点名称')),
                ('host', models.CharField(max_length=255, verbose_name='主机地址')),
                ('port', models.IntegerField(default=8000, verbose_name='端口')),
                ('role', models.CharField(choices=[('master', '主节点'), ('slave', '从节点')], default='slave', max_length=32, verbose_name='角色')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('maintenance', '维护')], default='offline', max_length=20, verbose_name='状态')),
                ('version', models.CharField(blank=True, default='', max_length=32, verbose_name='版本')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '集群节点',
                'verbose_name_plural': '集群节点',
                'ordering': ['name'],
            },
        ),
    ]
