# Generated by Django 5.2.14 on 2026-05-19 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_label', models.CharField(help_text='全局唯一标识，如 business-service', max_length=128, unique=True, verbose_name='应用标识')),
                ('name', models.CharField(max_length=255, verbose_name='组件名称')),
                ('version', models.CharField(blank=True, default='', max_length=64, verbose_name='当前版本')),
                ('host', models.CharField(blank=True, default='', help_text='业务服务的访问地址，如 http://10.0.0.2:8001', max_length=255, verbose_name='服务地址')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳')),
                ('upgrade_version', models.CharField(blank=True, default='', max_length=64, verbose_name='待升级版本')),
                ('upgrade_url', models.TextField(blank=True, default='', verbose_name='升级包下载地址')),
                ('upgrade_checksum', models.CharField(blank=True, default='', max_length=64, verbose_name='升级包 SHA-256')),
                ('extra_info', models.JSONField(blank=True, default=dict, verbose_name='附加信息')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '业务组件',
                'verbose_name_plural': '业务组件',
                'ordering': ['name'],
            },
        ),
    ]
