# Generated by Django 5.2.14 on 2026-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_servicecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecomponent',
            name='uninstall_pending',
            field=models.BooleanField(default=False, verbose_name='待卸载'),
        ),
    ]
