# Generated by Django 5.2.14 on 2026-05-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_center", "0002_alter_config_value_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="is_encrypted",
            field=models.BooleanField(
                default=False,
                help_text="开启后配置值将加密存储，API 返回 ***，编辑时不可见原值",
                verbose_name="加密存储",
            ),
        ),
    ]
