# Generated by Django 5.2.14 on 2026-05-17

from django.db import migrations


def migrate_encrypted_type(apps, schema_editor):
    Config = apps.get_model("config_center", "Config")
    for obj in Config.objects.filter(value_type="encrypted"):
        plaintext = obj.encrypted_value
        from djangoadminx.config_center.models import get_fernet
        try:
            f = get_fernet()
            value = f.encrypt(plaintext.encode()).decode()
        except RuntimeError:
            value = plaintext
        obj.is_encrypted = True
        obj.value_type = "string"
        obj.value = value
        obj.save(update_fields=["is_encrypted", "value_type", "value"])


class Migration(migrations.Migration):

    dependencies = [
        ("config_center", "0003_config_is_encrypted"),
    ]

    operations = [
        migrations.RunPython(migrate_encrypted_type),
    ]
