# Generated by Django 5.2.14 on 2026-05-11 09:58

import djangoadminx.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', djangoadminx.accounts.models.UserManager()),
            ],
        ),
    ]
