# Generated by Django 5.2.14 on 2026-05-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
    ]
