# Generated by Django 5.2.14 on 2026-05-16 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        db_index=True,
                        help_text="如 blog、crm，用于前端分组",
                        max_length=128,
                        verbose_name="应用标识",
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        help_text="如 blog:post:list，业务容器通过 introspect 获取",
                        max_length=255,
                        unique=True,
                        verbose_name="权限编码",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="权限名称")),
                ("desc", models.TextField(blank=True, default="", verbose_name="描述")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "业务权限",
                "verbose_name_plural": "业务权限",
                "ordering": ["app_label", "codename"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="business_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                to="accounts.businesspermission",
                verbose_name="业务权限",
            ),
        ),
    ]
