# Generated by Django 5.2.14 on 2026-05-11 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=512, verbose_name='原始文件名')),
                ('size', models.BigIntegerField(verbose_name='文件大小(bytes)')),
                ('mime_type', models.CharField(blank=True, default='', max_length=128, verbose_name='MIME 类型')),
                ('storage_backend', models.CharField(default='local', max_length=32, verbose_name='存储后端')),
                ('storage_path', models.CharField(max_length=1024, verbose_name='存储路径')),
                ('url', models.URLField(blank=True, default='', max_length=1024, verbose_name='访问 URL')),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=128, verbose_name='上传人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '文件记录',
                'verbose_name_plural': '文件记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
