# Generated by Django 5.2.14 on 2026-05-15 02:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0002_schedulejob_command_schedulejob_command_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳')),
                ('reload_pending', models.BooleanField(default=False, verbose_name='待重载')),
            ],
            options={
                'verbose_name': '调度器心跳',
                'verbose_name_plural': '调度器心跳',
            },
        ),
    ]
