# Generated by Django 5.2.14 on 2026-05-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webservice", "0003_schedulerheartbeat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulejob",
            name="webservice",
        ),
        migrations.RemoveField(
            model_name="webservicelog",
            name="webservice",
        ),
        migrations.AlterField(
            model_name="schedulejob",
            name="handler",
            field=models.CharField(
                blank=True,
                default="",
                help_text="如 djangoadminx.webservice.tasks.ntp_sync",
                max_length=255,
                verbose_name="处理函数",
            ),
        ),
        migrations.DeleteModel(
            name="WebService",
        ),
        migrations.DeleteModel(
            name="WebServiceLog",
        ),
    ]
