# Generated by Django 5.2.14 on 2026-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webservice", "0004_remove_schedulejob_webservice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulejob",
            name="handler",
            field=models.CharField(
                blank=True,
                default="",
                help_text="如 djangoadminx.jobs.tasks.ntp_sync",
                max_length=255,
                verbose_name="处理函数",
            ),
        ),
    ]
