# Generated by Django 5.2.14 on 2026-05-16 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_business_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        db_index=True,
                        help_text="如 blog、crm",
                        max_length=128,
                        verbose_name="应用标识",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="菜单显示名称", max_length=255, verbose_name="名称"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ant Design 图标名，如 FileTextOutlined",
                        max_length=128,
                        verbose_name="图标",
                    ),
                ),
                (
                    "menu_path",
                    models.CharField(
                        help_text="如 /plugins/blog，侧边栏点击后跳转至此",
                        max_length=255,
                        verbose_name="前端路由",
                    ),
                ),
                (
                    "allowed_paths",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text='JSON 数组，如 ["GET:/api/v1/blog/*","POST:/api/v1/blog/*"]',
                        verbose_name="路径白名单",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "业务命令",
                "verbose_name_plural": "业务命令",
                "ordering": ["app_label", "name"],
                "unique_together": {("app_label", "menu_path")},
            },
        ),
    ]
