# Generated by Django 5.2.14 on 2026-05-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_business_command"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="code",
        ),
    ]
