# Generated by Django 5.2.14 on 2026-05-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_role_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_page",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="首页路径"
            ),
        ),
    ]
