# Generated by Django 5.2.14 on 2026-05-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_home_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="系统内置角色不可编辑或删除",
                verbose_name="系统内置",
            ),
        ),
    ]
